# Generated by Django 2.2.16 on 2020-11-23 16:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0006_auto_20201115_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 16, 33, 26, 394332, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
